### Create a new user
POST  http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "ssfd1@asdf.aa",
    "password": "ok"
}

### SignIn 
POST  http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "ssfd1@asdf.aa",
    "password": "ok"
}


### Get a user
GET http://localhost:3000/auth/11


### Get users
GET http://localhost:3000/auth?email=ssfd@asdf.aa

### Update user
PATCH http://localhost:3000/auth/10
Content-Type: application/json

{
    "passdsfsdfword": "asssdf"
}

### Delete user
DELETE http://localhost:3000/auth/10