### Create a new user
POST  http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "ssfd@asdf.aa",
    "password": "ok"
}

### Get a user
GET http://localhost:3000/auth/sdsd


### Get users
GET http://localhost:3000/auth?email=ssfd@asdf.asdf

### Update user
PATCH http://localhost:3000/auth/11
Content-Type: application/json

{
    "password": "asssdf"
}

### Delete user
DELETE http://localhost:3000/auth/8